[package]
name = "fortytwo_lang"
version = "0.1.0"
authors = ["linuskmr <56581587+linuskmr@users.noreply.github.com>"]
edition = "2021"
# default-run = "main"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
miette = { version = "3.2", features = ["fancy"] }
thiserror = "1.0"
